services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: pg-practica1
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: practica1
      POSTGRES_DB: practica1

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
